<?php

/**
 * @file
 * Install file for core.
 */

use Drupal\drupal_helpers\Feature;

/**
 * Implements hook_install().
 */
function mysite_core_install() {
  if (!module_exists('drupal_helpers')) {
    module_enable(['drupal_helpers']);
  }

  $functions = get_defined_functions();
  foreach ($functions['user'] as $function) {
    if (strpos($function, 'mysite_core_update_') === 0) {
      call_user_func($function);
    }
  }
}

/**
 * Reverts core feature.
 */
function mysite_core_update_7000() {
  Feature::revert('mysite_core');
}
